export const interests = [
    'Affinity Networks',
    'Art',
    'Arts and Crafts',
    'Board Games',
    'Business',
    'College Sports',
    'Cooking',
    'Cryptocurrency/Blockchain',
    'Engineering',
    'Fitness and Nutrition',
    'Foreign Languages',
    'Home Improvement',
    'Innovation',
    'Leadership',
    'Management',
    'Meditation',
    'Music - Listening',
    'Music - Playing Instruments',
    'Music - Singing',
    'Outdoor Recreation',
    'Parenting',
    'Pop Culture',
    'Professional Sports',
    'Reading',
    'Social Impact',
    'Sports - Playing Sports',
    'Technology',
    'Travel',
    'University and College Pride',
    'Video Games',
    'Yoga',
    'Zall Gives Back'];

// export const interests = [
//   'Archery',
//   'Badminton',
//   'Baseball',
//   'Basketball',
//   'Bowling',
//   'Boxing',
//   'Brazilian Jiu-Jitsu',
//   'Cricket',
//   'Dodgeball',
//   'Fencing',
//   'Football',
//   'Golf',
//   'Ice Skating / Figure Skating',
//   'Karate',
//   'Kickboxing',
//   'Lacrossse',
//   'MMA',
//   'Muay Thai',
//   'Ping Pong',
//   'Rowing',
//   'Rugby',
//   'Soccer',
//   'Tai Chi',
//   'Tennis',
//   'Volleyball',
//   'WWE',
//   '49ers',
//   'Anaheim Angels',
//   'Anaheim Ducks',
//   'Arsenal FC',
//   'Baltimore Orioles',
//   'Baltimore Ravens',
//   'Boston Celtics',
//   'Boston Red Sox',
//   'Carolina Panthers',
//   'Chelsea FC',
//   'Chicago Bears',
//   'Chicago Blackhawks',
//   'Chicago Bulls',
//   'Chicago Cubs',
//   'Cincinnati Bengals',
//   'Cincinnati Reds',
//   'Cleveland Browns',
//   'Cleveland Cavaliers',
//   'Colorado Avalanche',
//   'Colorado Rapids',
//   'Colorado Rockies',
//   'Dallas Cowboys',
//   'Denver Broncos',
//   'Detroit Lions',
//   'Detroit Tigers',
//   'Duke Blue Devils',
//   'FC Barcelona',
//   'FC Bayern München',
//   'Golden State Warriors',
//   'Green Bay Packers',
//   'Indianapolis Colts',
//   'Kansas City Chiefs',
//   'Kansas City Royals',
//   'L.A. Kings',
//   'L.A. Lakers',
//   'Liverpool FC',
//   'Los Angeles Dodgers',
//   'Manchester United',
//   'Miami Dolphins',
//   'Minnesota Vikings',
//   'Minnesota Wild',
//   'Montreal Canadiens',
//   'Nashville Predators',
//   'New England Patriots',
//   'New Orleans Saints',
//   'New York Giants',
//   'New York Jets',
//   'New York Knicks',
//   'New York Mets',
//   'New York Rangers',
//   'New York Red Bulls',
//   'New York Yankees',
//   'Oakland A\'s',
//   'Oakland Raiders',
//   'Philadelphia Eagles',
//   'Philadelphia Flyers',
//   'Pittsburgh Penguins',
//   'Pittsburgh Steelers',
//   'Portland Trail Blazers',
//   'Sacramento Kings',
//   'San Jose Sharks',
//   'Seattle Mariners',
//   'Seattle Sonics',
//   'Seattle Sounders',
//   'SF Giants',
//   'St. Louis Cardinals',
//   'Tampa Bay Buccaneers',
//   'Tampa Bay Rays',
//   'Toronto Blue Jays',
//   'Tottenham Hotspur FC',
//   'Washington Capitals',
//   'Washington Nationals',
//   'Washington Redskins',
//   'Washington Wizards',
//   'Acting/improv',
//   'Feminism',
//   'Festivals',
//   'Fitness',
//   'History',
//   'Marathons',
//   'Meditation',
//   'Neuroscience',
//   'Nutrition',
//   'Parenting',
//   'Philosophy',
//   'Photography',
//   'Podcasts',
//   'Real Estate',
//   'Self Improvement',
//   'Space',
//   'Sustainability',
//   'Tiny Homes',
//   'Travel',
//   'Trivia',
//   'Veganism',
//   'Vegetarianism',
//   'Videography/Cinematography',
//   'Writing',
//   'Yoga',
//   'Auburn University',
//   'Boston College',
//   'Brigham Young University',
//   'Brown University',
//   'Cal Poly',
//   'Carnegie Mellon University',
//   'Central Washington University',
//   'Clemson University',
//   'Columbia University',
//   'Connecticut College',
//   'Cornell University',
//   'Dartmouth College',
//   'Duke University',
//   'Eastern Washington University',
//   'Florida State University',
//   'Fordham University',
//   'Georgetown University',
//   'Georgia Tech',
//   'Gonzaga University',
//   'Indiana University',
//   'Kansas State University',
//   'Kent State University',
//   'Massachusetts Institute of Technology',
//   'Miami University',
//   'Nebraska Wesleyan',
//   'New York University',
//   'Northeastern University Boston',
//   'Northwestern University',
//   'Notre Dame Fighting Irish',
//   'Occidental College',
//   'Ohio State University',
//   'Ohio University',
//   'Oregon State',
//   'Penn State',
//   'Princeton University',
//   'Rice University',
//   'Rochester Institute of Technology',
//   'San Diego State University',
//   'San Francisco State University',
//   'Santa Clara Univerity',
//   'Seattle Pacific University',
//   'Seattle University',
//   'Southern Methodist University',
//   'Stanford University',
//   'Syracuse University',
//   'Texas A&M University',
//   'Texas Tech University',
//   'Tufts University',
//   'Univerisity of North Dakota',
//   'University of Arizona',
//   'University of British Columbia',
//   'University of California Berkeley',
//   'University of California Irvine',
//   'University of California Los Angeles',
//   'University of California San Diego',
//   'University of California Santa Barbara',
//   'University of Central Florida',
//   'University of Cincinnati',
//   'University of Colorado',
//   'University of Connecticut',
//   'University of Florida',
//   'University of Georgia',
//   'University of Idaho',
//   'University of Iowa',
//   'University of Kansas',
//   'University of Kentucky',
//   'University of Massachusetts',
//   'University of Michigan',
//   'University of Missouri',
//   'University of Montana',
//   'University of Nebraska',
//   'University of Oregon',
//   'University of Pennsylvania',
//   'University of Puget Sound',
//   'University of Redlands',
//   'University of Rochester',
//   'University of South Carolina',
//   'University of Southern California',
//   'University of Texas at Austin',
//   'University of Toronto',
//   'University of Washington',
//   'Vanderbilt University',
//   'Villanova University',
//   'Washington University in St.Louis',
//   'Western Washington University',
//   'Whitman College',
//   'Wichita State',
//   'Yale University',
//   'Bass',
//   'Bluegrass',
//   'Classical',
//   'DJing / Producing Music',
//   'Drumming',
//   'Electric Guitar',
//   'Electronic/Dance Music',
//   'Guitar',
//   'Hip-Hop/Rap',
//   'Indie Rock',
//   'Jazz',
//   'Live Music',
//   'Musical Theatre',
//   'New Wave',
//   'Piano',
//   'Ukelele',
//   'Art',
//   'Arts and Crafts',
//   'Backpacking',
//   'Bagpiping',
//   'Baking',
//   'Ballet',
//   'Board Games',
//   'Boating',
//   'Brewing Beer',
//   'Camping',
//   'Chess',
//   'Cooking',
//   'Crosswords',
//   'Cycling',
//   'Dancing',
//   'Fishing',
//   'Flying',
//   'Gardening',
//   'Geocaching',
//   'Hiking',
//   'Home Improvement',
//   'Horseback Riding',
//   'Hunting',
//   'Kayaking',
//   'Knitting',
//   'Outdoor Recreation',
//   'Reading',
//   'Rock climbing',
//   'Running',
//   'Sailing',
//   'Shuffleboard',
//   'Singing',
//   'Skateboarding',
//   'Skiing/Snowboarding',
//   'Surfing',
//   'Swimming',
//   'Ultimate Frisbee',
//   'Video Games',
//   'Backgammon',
//   'Bacon',
//   'Bagels',
//   'BBQ',
//   'Beer',
//   'Bourbon',
//   'Cereal',
//   'Cheese',
//   'Dessert',
//   'Dining out',
//   'Donuts',
//   'Fine Dining',
//   'Indian Food',
//   'Pastry',
//   'Premium Coffee',
//   'Sushi',
//   'Tacos',
//   'Tea',
//   'Whisky',
//   'Wine',
//   'Food Trucks',
//   'Arrested Development',
//   'Batman',
//   'Battlestar Galactica',
//   'Beyonce',
//   'Anime',
//   'Burning Man',
//   'Comics',
//   'Dexter',
//   'Disney',
//   'Friday Night Lights',
//   'Friends',
//   'Game of Thrones',
//   'Grey\'s Anatomy',
//   'Harry Potter',
//   'Homeland',
//   'Interstellar',
//   'Lifetime Movies',
//   'New Girl',
//   'Nintendo',
//   'Orange is the New Black',
//   'Outlander',
//   'Smash Bros',
//   'Star Trek',
//   'Star Wars',
//   'Superman',
//   'The Bachelor',
//   'The Simpsons',
//   'TMNT',
//   'Transformers',
//   'Twin Peaks',
//   'Walking Dead',
//   'You Tube',
//   'Agent Platform',
//   'B2B',
//   'B2C',
//   'Back End Development',
//   'Business Development',
//   'Data Analysis',
//   'Email Marketing',
//   'Front end Development',
//   'Leadership',
//   'Product Management',
//   'Project Management',
//   'Rentals',
//   'Sales Operations',
//   'SEO Marketing',
//   'Team Building',
//   'User Experience Design',
//   'Zall Gives Back',
//   '3D Printing',
//   'Android',
//   'Arduino',
//   'AWS',
//   'C#',
//   'git',
//   'IOS',
//   'Javascript',
//   'Mobile development',
//   'Mobile web',
//   'Node.js',
//   'PHP',
//   'Python',
//   'React',
//   'Ruby',
//   'Splunk',
//   'SQL',
//   'UAV & Drones',
//   'Web Development',
//   'Web Pak',
//   'ZG Asian Affinity Network',
//   'ZG Black/African Ancestry Network',
//   'ZG Chinese Network',
//   'ZG Disability Network',
//   'ZG Latinx/Hispanic Network',
//   'ZG LGBTQ+ Network',
//   'ZG Multigenerational Network',
//   'ZG Veterans Network',
//   'ZG Women\'s Network',
//   'ZG Women in Engineering Network'
// ];

export function matchStateToTerm(interest, value) {
  return (
    interest.toLowerCase().indexOf(value.toLowerCase()) !== -1
  );
}

export function upperCaseFirstLetter(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

export const createCookie = (name, value, days) => {
  let expires;
  if (days) {
    const date = new Date();
    date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
    expires = `; expires=${date.toGMTString()}`;
  } else {
    expires = '';
  }
  document.cookie = `${name}=${value}${expires}; path=/`;
};

export const getCookies = () => {
  return document.cookie.split(';').reduce((p,c) => {
    let cookie = c.split('=');
    p[cookie[0].trim()] = cookie[1];
    return p;
  }, {});
};
